# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-11
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Xcode version
        # You may pin to the exact commit or the version.
        # uses: maxim-lobanov/setup-xcode@9a697e2b393340c3cacd97468baa318e4c883d98
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          # Version of Xcode to use
          xcode-version: "11.7.0"
    
      - name: Prepare Theos
        # Don't use @main in production, this repo is specifically for testing it.
        uses: Randomblock1/theos-action@v1.3

      - name: Build package
        run: |
          rm -f packages/*
          make package

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: "Package built by macos"
          path: ${{ github.workspace }}/packages/*.deb
